/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school1.pkg0;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static jdk.nashorn.internal.runtime.Debug.id;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author abou
 */
public class ListeEtudiant extends javax.swing.JFrame {

         SCHOOL10 scl= new SCHOOL10();
Statement stm=null;
Connection conect=null;
    ResultSet Rst=null;
     PreparedStatement ps=null;
    static String test;
    public ListeEtudiant() {
          initComponents();
          affichageEtudiant();
          conect=scl.obtenirconnexion();
                    }
    public void  affichageEtudiant(){
                   try {
                             
                             stm=scl.obtenirconnexion().createStatement();
   
        ResultSet Rst=stm.executeQuery("Select *from etudiant");
                              tableEtudiant.setModel(DbUtils.resultSetToTableModel(Rst));
                              

            }
    
    catch(Exception e1){
             {System.out.println(e1);
             }
    }
    }
    public void infoEtudiant(){
         try {
               int row=tableEtudiant.getSelectedRow();
               this.test=(tableEtudiant.getModel().getValueAt(row,0).toString());
               String requet="select *from etudiant where idEtudiant='"+test+"'";
                ResultSet Rst=stm.executeQuery(requet);
                if(Rst.next()){
                String i1=Rst.getString("idEtudiant");
                txtidE.setText(i1);
                 String i2=Rst.getString("nomEtudiant");
                txtnom.setText(i2);
                 String i3=Rst.getString("prenomEtudiant");
                txtprenom.setText(i3);
                 String i4=Rst.getString("idInscription");
                txtidi.setText(i4);
                 String i5=Rst.getString("dateInscription");
                txtdate.setText(i5);
                 String i6=Rst.getString("noteEtudiant");
                txtnote.setText(i6);
                 String i7=Rst.getString("assidute");
                txtassidute.setText(i7);
                 String i8=Rst.getString("evaluation");
                txtevaluation.setText(i8);
                }
            }
    
    catch(Exception e1){
             System.out.println(e1);
             }
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEtudiant = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtidE = new javax.swing.JLabel();
        txtprenom = new javax.swing.JLabel();
        txtidi = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtassidute = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnote = new javax.swing.JLabel();
        txtnom = new javax.swing.JLabel();
        txtdate = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtevaluation = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        idE = new javax.swing.JTextField();
        nomE = new javax.swing.JTextField();
        prenomE = new javax.swing.JTextField();
        idiE = new javax.swing.JTextField();
        diE = new javax.swing.JFormattedTextField();
        jButton4 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("SUPPRIMER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 90, 30));

        tableEtudiant.setBackground(new java.awt.Color(40, 156, 210));
        tableEtudiant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableEtudiant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEtudiantMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableEtudiant);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 760, 90));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("information Etudiant"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtidE, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 117, 14));
        jPanel1.add(txtprenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 180, 120, 14));
        jPanel1.add(txtidi, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 220, 110, 14));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("id_Inscription");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));
        jPanel1.add(txtassidute, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 143, 14));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Evaluation");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Prenom");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 180, 40, -1));
        jPanel1.add(txtnote, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 300, 110, 14));
        jPanel1.add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 130, 130, 14));
        jPanel1.add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 260, 130, 14));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Note");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Assidute");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));
        jPanel1.add(txtevaluation, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 143, 14));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Date_Inscription");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("id_Etudiant");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nom");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\abou\\Documents\\NetBeansProjects\\SCHOOL1.0\\panel.png")); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 450));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 260, 450));

        jButton2.setText("MODIFIER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 90, 30));

        jButton3.setText("RECHERCHE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 100, 30));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Id_etudiant");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nom_etudiant");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Prenom_etudiant");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Id_inscription");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Date_inscription");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));
        getContentPane().add(idE, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 130, -1));
        getContentPane().add(nomE, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 130, -1));
        getContentPane().add(prenomE, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 130, -1));

        idiE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idiEActionPerformed(evt);
            }
        });
        getContentPane().add(idiE, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 130, -1));
        getContentPane().add(diE, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 130, -1));

        jButton4.setText("INSCRIRE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 90, 30));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("( AAAAMMJJ Ex:20180426)");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\abou\\Documents\\NetBeansProjects\\SCHOOL1.0\\liste.png")); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 500, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try{
              String requet="delete from etudiant where idEtudiant=?";
            ps=conect.prepareStatement(requet);
            ps.setString(1,txtidE.getText());
            ps.execute();
             System.out.println("supprimer");
                JOptionPane.showMessageDialog(null, "supprimer");
        }
        catch(Exception e1){
             System.out.println(e1);
             }
        infoEtudiant();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tableEtudiantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEtudiantMouseClicked
       infoEtudiant();
    }//GEN-LAST:event_tableEtudiantMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Nouveau_etudiant netud= new Nouveau_etudiant();
        netud.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void idiEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idiEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idiEActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String id=idE.getText();
        String nom=nomE.getText();
        String prenom=prenomE.getText();
        String idi=idiE.getText();
        String die=diE.getText();

        String requete="INSERT INTO etudiant(idEtudiant, nomEtudiant,prenomEtudiant,idInscription,dateInscription) VALUES ('"+id+"','"+nom+"','"+prenom+"','"+idi+"','"+die+"')";
        try{
            stm.executeUpdate(requete);
            JOptionPane.showMessageDialog(null," inscris");
            idE.setText("");nomE.setText("");prenomE.setText("");
            idiE.setText("");diE.setText("");
            Paiement paie= new Paiement();
            paie.setVisible(rootPaneCheckingEnabled);
            new Nouveau_etudiant();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            String id=idE.getText();
            String requet="SELECT * From etudiant WHERE  idEtudiant='"+id+"'";
            
      
       conect=scl.obtenirconnexion();
       stm=conect.createStatement();
       Rst=stm.executeQuery(requet);
       while(Rst.next()){
           nomE.setText(Rst.getString(2));
           prenomE.setText(Rst.getString(3));
           idiE.setText(Rst.getString(4));
           diE.setText(Rst.getString(5));
           
       }
       
       
        }    catch (SQLException ex) {
                 Logger.getLogger(ListeEtudiant.class.getName()).log(Level.SEVERE, null, ex);
             }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListeEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListeEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListeEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListeEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListeEtudiant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField diE;
    private javax.swing.JTextField idE;
    private javax.swing.JTextField idiE;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomE;
    private javax.swing.JTextField prenomE;
    private javax.swing.JTable tableEtudiant;
    private javax.swing.JLabel txtassidute;
    private javax.swing.JLabel txtdate;
    private javax.swing.JLabel txtevaluation;
    private javax.swing.JLabel txtidE;
    private javax.swing.JLabel txtidi;
    private javax.swing.JLabel txtnom;
    private javax.swing.JLabel txtnote;
    private javax.swing.JLabel txtprenom;
    // End of variables declaration//GEN-END:variables
}
